
import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "../globals.css";
import Footer from "@/components/shared/home/footer";
import NavigationBar from "@/components/shared/home/NavigationBar";
import { ReduceProvider } from "@/providers/ReduxProvider";



    const poppins = Poppins({
      subsets: ['latin'],
      display: 'swap', 
      variable: '--font-poppins',
      weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    });




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} `}
      >
        
        <ReduceProvider>

        <NavigationBar />
        {children}
        <Footer />
        </ReduceProvider>
      </body>
    </html>
  );
}
